package com.docuflow.core.entity;

public enum WebhookEventType {
    DOCUMENT_UPLOADED,
    DOCUMENT_PROCESSING_STARTED,
    DOCUMENT_PROCESSING_COMPLETED,
    DOCUMENT_PROCESSING_FAILED,
    DOCUMENT_REVIEW_REQUIRED,
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    EXTRACTION_COMPLETED,
    WEBHOOK_DELIVERY_FAILED
}